name: Auto Version Increment

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'VERSION'  # Ignore pushes that only change the VERSION file to avoid infinite loops

jobs:
  increment-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed for pushing changes
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for proper versioning
      
      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
      
      - name: Read current version
        id: version
        run: |
          VERSION=$(cat VERSION)
          echo "Current version: $VERSION"
          echo "current_version=$VERSION" >> $GITHUB_OUTPUT
      
      - name: Increment version
        id: increment
        run: |
          # Parse the version components
          IFS='.' read -r MAJOR MINOR PATCH <<< "${{ steps.version.outputs.current_version }}"
          
          # Increment the patch version
          NEW_PATCH=$((PATCH + 1))
          NEW_VERSION="$MAJOR.$MINOR.$NEW_PATCH"
          
          echo "New version: $NEW_VERSION"
          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT
      
      - name: Update VERSION file
        run: |
          echo "${{ steps.increment.outputs.new_version }}" > VERSION
      
      - name: Commit and push changes
        run: |
          git add VERSION
          git commit -m "Auto increment version to ${{ steps.increment.outputs.new_version }}"
          git push
